### ISSUE TITLE
Changes in commit or pull request?

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [touchifyapp/vsts-changed-files#38]
Hi

My "issue" is more of a question: Does this extension look for files that changed in the triggering/latest commit or files that changed in the pull request that triggered the pipeline? I'm interested in having specific jobs of my PR pipeline only run if certain files changed in the PR. I couldn't really find out by reading the documentation or source code.

Best regards
Jens

**Comment by remanation** [comment]
This is what I figured out by playing a bit with it today:

- It seems to check files changed for in commits.
- This also mean that if you changed a file in one commit and "revert" the changed in a different commit - the file will still be flagged as changed.

**Comment by SomaticIT** [comment]
Hello,

This extension has two modes:
1. Detect changes since the last successful build (default mode)
2. Detect changes between two branches (https://github.com/touchifyapp/vsts-changed-files#multi-branch-usage)

When using the default mode, the behavior is to browse every commits one by one to detect changes (revert changes are taking into account).

When using the multi-branch mode, the behavior is to ask git for the diff between the two branches (revert changes should not be taken into account).

Is it OK for you?

Thanks

**Comment by jenskuhrjorgensen** [comment]
Hi @SomaticIT 

That was exactly what we were looking for. Thanks a lot for pointing that out!

**Comment by remanation** [comment]
Thanks @SomaticIT seems to work like the behavior we wanted to achieve 👍
